# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/macrolearner',
                'doc_host': 'https://iamsurajkumar.github.io',
                'git_url': 'https://github.com/iamsurajkumar/macrolearner',
                'lib_path': 'macrolearner'},
  'syms': {'macrolearner.core': {'macrolearner.core.foo': ('core.html#foo', 'macrolearner/core.py')}}}
